apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vulcanami

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-deployment.yaml
  - ingress.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml

commonLabels:
  app.kubernetes.io/name: vulcanami
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/musicmonk42/vulcanami_llm-api
    newTag: latest
